use correct condpriority to fix cond class exclusion
OasisLMF/OasisLMF pull request #1119
Opened 2022-10-14 09:31 UTC by sstruzik

### Fix for cond class exclusion when multiple priority are used
Add a loop breaker in case account cond hierarchy lead to cycling cond tag infinitely.

example of oed that had issue treating cond class:
[account.csv](https://github.com/OasisLMF/OasisLMF/files/9784457/account.csv)
[location.csv](https://github.com/OasisLMF/OasisLMF/files/9784458/location.csv)

2022-10-18 14:20 UTC, johcarter commented
Fixes #1122 , and tests all pass

2022-11-04 15:55 UTC, mtazzari requested changes
Quantitative tests were conducted by Joh, and she reported that they pass as expected.
So here I've just reviewed code style.
It'd be great if you could add perhaps a small comment  as indicated.

2022-11-04 15:55 UTC, mtazzari commented on oasislmf/preparation/il_inputs.py
> +    if cond_class in accounts_df.columns:
can you add a small (even one-liner) comment about the logic of what we're doing here below?
either before the `if` or inside each case, so it is clear what action has to be taken depending on whether `cond_class` is in `df.columns`.
e.g.
```py
if cond_class in accounts_df.columns:
    # in this case, we ...
else:
    # ...

2022-11-04 15:55 UTC, mtazzari commented on oasislmf/preparation/il_inputs.py
> +    policy_df = accounts_df.drop_duplicates(subset=[portfolio_num, acc_num, policy_num, 'layer_id']).drop(columns=[cond_tag, 'condpriority'])
please add a short comment before these manipulations of `accounts_df` to explain what we need to achieve.

2022-11-07 10:57 UTC, mtazzari approved these changes

2022-11-07 10:58 UTC, merged