Feature/account terms [WIP]
OasisLMF/OasisLMF pull request #1235
Opened 2023-03-06 15:20 UTC by sstruzik

### Release notes feature title
... Release notes description / summary
... Any text between these two tags will be automatically pulled into the platform release notes

2023-03-10 10:49 UTC, johcarter commented
@sstruzik I've fixed ODS validation issues with the insurance_accounts test so that it can be run on your branch.  I'll let you know of any issues I find with numerical results as they arise

2023-03-10 13:40 UTC, johcarter approved these changes
Numbers look good, just need to add insurance_account fm validation test to ci, ideally with the DRs 0.25 0.5 0.75 1

2023-03-13 10:55 UTC, mtazzari approved these changes
I see that Joh signed it off, so I understand it the PR produces the desired results.
I have no code comments, just docstrings are missing in many places.
I've added comments in some but not all the functions that lack docstrings.
In some places the entire docstring is missing, in some places just the argument types, etc.

2023-03-13 10:55 UTC, mtazzari commented on oasislmf/pytools/fm/back_allocation.py
> +    """
Missing data types of all arguments.

2023-03-13 10:55 UTC, mtazzari commented on oasislmf/pytools/fm/back_allocation.py
> +
Missing data types of all arguments.

2023-03-13 10:55 UTC, mtazzari commented on oasislmf/pytools/fm/back_allocation.py
> +    back allocation of loss to the base children
The function doesn't return anything, so I presume it modifies some arrays in place.
I think it'd be good to make it clear in the docstring, like 
```suggestion
    back allocation of loss to the base children. The function modifies in-place array xyz.
```

2023-03-13 10:55 UTC, mtazzari commented on oasislmf/pytools/fm/back_allocation.py
> +        temp_node_extras_layer_merge_save: node extra before profile
missing all data types

2023-03-13 10:55 UTC, mtazzari commented on oasislmf/pytools/fm/back_allocation.py
> +
The function doesn't return anything, perhaps mention in the docstring which arrays are updated in-place.

2023-03-13 10:55 UTC, mtazzari commented on oasislmf/pytools/fm/compute_sparse.py
> +        temp_children_queue: empty array where we write base children.
missing data types

2023-03-13 10:55 UTC, mtazzari commented on oasislmf/pytools/fm/compute_sparse.py
> +        number of base children
missing return data type

2023-03-13 10:55 UTC, mtazzari commented on oasislmf/pytools/fm/compute_sparse.py
>      sidx_created = False
missing docstring, arguments etc

2023-03-13 10:55 UTC, mtazzari commented on oasislmf/pytools/fm/compute_sparse.py
>      sidx_created = False
missing docstring, arguments, etc

2023-03-13 10:55 UTC, mtazzari commented on oasislmf/pytools/fm/compute_sparse.py
>      parent = nodes_array[parent_id]
missing docstring, arguments etc

2023-03-13 10:55 UTC, mtazzari commented on oasislmf/pytools/fm/compute_sparse.py
>                    stepped):
missing docstring, arguments, etc

2023-03-13 10:55 UTC, mtazzari commented on oasislmf/pytools/fm/compute_sparse.py
>      # extras_indptr = computation_structure.extras_indptr
I'd clean up all this unneeded stuff

2023-03-13 12:52 UTC, sambles requested changes
Only one minor nitpick, in the expected results there are `*.npy` added in this PR

 under [validation/insurance_account/expected/output](https://github.com/OasisLMF/OasisLMF/tree/feature/account_terms/validation/insurance_account/expected/output)

I'd remove those files: (unless needed for something?) 
* [fm_profile.npy](https://github.com/OasisLMF/OasisLMF/blob/feature/account_terms/validation/insurance_account/expected/output/fm_profile.npy)
* [node_parents_array_2.npy](https://github.com/OasisLMF/OasisLMF/blob/feature/account_terms/validation/insurance_account/expected/output/node_parents_array_2.npy)
* [node_profiles_array_2.npy](https://github.com/OasisLMF/OasisLMF/blob/feature/account_terms/validation/insurance_account/expected/output/node_profiles_array_2.npy)
* [nodes_array_2.npy](https://github.com/OasisLMF/OasisLMF/blob/feature/account_terms/validation/insurance_account/expected/output/nodes_array_2.npy)
* [output_array_2.npy](https://github.com/OasisLMF/OasisLMF/blob/feature/account_terms/validation/insurance_account/expected/output/output_array_2.npy)

And add the `*.npy` extension to the `.gitignore` file

2023-03-14 09:28 UTC, merged