Fix: undo 100% correlation if no correlation setting provided in model settings
OasisLMF/OasisLMF pull request #1584
Opened 2024-10-25 13:15 UTC by sstruzik

### Fix: undo 100% correlation if no correlation setting provided in model settings
The hazard_group_id where not generated if the correlation settings were not provided, causing a 100% correlation across all location.
This fix assure the  hazard_group_id are generated and used correctly in gulmc.

2024-10-30 21:30 UTC, benhayes21 approved these changes

2024-10-31 12:12 UTC, johcarter commented
The correlation file is being generated when correlation_settings are missing from model settings on the fixed branch, which is the expected behaviour.

I see another separate issue here, which is the damage_group_id and hazard_group_ids are identical when data settings are the same for hazard and damage.  This would mean that the same random numbers would be used to seed hazard and damage sampling, which would induce unwanted correlation between hazard and damage per sample.  Although we may want the logical groupings to be the same, we want a different hash to prevent this correlation from occurring.

proposed fix is to add a constant to the hashing algorithm to force hazard group_ids to be different to damage group ids, but leave the damage group id hashing as it is.
FYI @benhayes21

2024-10-31 12:15 UTC, johcarter requested changes
issue fixed, but also need to hash hazard_group_id differently to damage_group_id when data settings are identical

2024-10-31 14:25 UTC, johcarter approved these changes
even though hazard_group_id and damage_group_id may be the same, we've checked that the random numbers are seeded differently, which is what we need. No changes needed

2024-10-31 15:38 UTC, merged